// src/utils/knownSpamPhrases.js

// Daftar frasa Judol/Spam yang lebih spesifik untuk fuzzy matching.
// Semua kata tunggal dan frasa ambigu (seperti 'akun pro') telah dihapus
// untuk mencegah false positive. Basis pengetahuan ini adalah hasil
// dari analisis observasional terhadap tren komentar spam di YouTube Indonesia.
export const knownSpamPhrasesSimple = [
    // === Ajakan & Instruksi ===
    // Frasa-frasa ini menciptakan urgensi (call-to-action) dan secara
    // langsung mengarahkan pengguna untuk melakukan tindakan tertentu,
    // seperti mengunjungi profil atau mengklik tautan.
    'daftar sekarang',
    'daftar gratis',
    'pendaftaran gratis',
    'registrasi sekarang',
    'buat akun sekarang',
    'klik link di profil',
    'klik link di bio',
    'klik tautan di profil',
    'kunjungi link di bio',
    'link pendaftaran di bio',
    'link ada di bio',
    'linknya di profil',
    'info lengkap di bio',
    'silahkan cek bio',
    'cek bio sekarang',
    'cek profil sekarang',
    'gabung sekarang',
    'join sekarang juga',
    'join grup wa',
    'masuk grup whatsapp',
    'add wa admin',
    'chat via whatsapp',
    'info lanjut wa',
    'link grup telegram',
    'join tele',
    'grup tele',
    'chat admin sekarang',
    'hubungi admin kami',
    'hubungi cs kami',
    'kontak admin',
    'tanya admin',
    'dm admin untuk info',
    'inbox untuk daftar',
    'kunjungi situs kami',
    'kunjungi website kami',
    'download aplikasi',
    'install aplikasinya',
    'mainkan sekarang',
    'coba sekarang',
    'main di sini',
    'rasakan sensasinya',
    'buktikan sendiri',
    'ambil bonusmu',
    'klaim sekarang',
    'jangan sampai ketinggalan',
    'info selengkapnya',

    // === Bonus & Promosi ===
    // Taktik ini menargetkan keinginan pengguna untuk mendapatkan keuntungan
    // instan atau gratis. Kata-kata seperti 'bonus', 'gratis', dan 'kaget'
    // sangat umum digunakan untuk menarik perhatian.
    'bonus new member',
    'bonus member baru',
    'bonus selamat datang',
    'bonus deposit 100',
    'bonus deposit harian',
    'bonus deposit pertama',
    'bonus harian',
    'bonus mingguan',
    'bonus bulanan',
    'bonus referral',
    'bonus referal seumur hidup',
    'bonus rollingan',
    'bonus turnover',
    'bonus cashback',
    'cashback mingguan',
    'garansi kekalahan 100',
    'garansi modal kembali',
    'saldo gratis',
    'freebet gratis',
    'freespin gratis',
    'chip gratis',
    'dana kaget',
    'link dana kaget',
    'klaim bonus sekarang',
    'event bagi bagi saldo',
    'promo terbesar',
    'promo menarik',
    'promo spesial',
    'promo terbatas',
    'hadiah menarik',
    'hadiah jutaan rupiah',
    'menangkan hadiah',
    'dapatkan bonus',
    'ambil bonus harian',
    'tanpa turnover',
    'syarat mudah',
    'tanpa syarat',
    'cuma modal receh',
    'modal 10k',
    'depo 25 bonus 25',
    'depo 50 bonus 50',
    'bonus slot 100',
    'extra bonus',
    'dapat bonus',
    'cuan gratis',
    'giveaway saldo',

    // === Kemenangan & Keuntungan ===
    // Frasa ini menjual janji kemenangan mudah dan keuntungan besar,
    // menargetkan aspek psikologis pengguna yang ingin cepat kaya.
    // Istilah 'WD' (Withdraw) dan 'JP' (Jackpot) adalah jargon umum.
    'jp pasti cair',
    'pasti bayar',
    'dijamin wd',
    'wd cepat',
    'gampang menang',
    'pasti maxwin',
    'server gampang menang',
    'winrate tertinggi',
    'modal kecil untung besar',
    'modal receh jadi sultan',
    'bukti jp member',
    '100 dijamin bayar',
    'kemenangan sensational',

    // === Istilah Judi & Game (Hanya Frasa) ===
    // Ini adalah frasa-frasa yang mengandung istilah spesifik dari dunia
    // perjudian online. Menggunakan frasa (bukan kata tunggal) membantu
    // mengurangi false positive, misalnya pada kata 'gacor' atau 'akun'.
    'slot online terpercaya',
    'togel online resmi',
    'live casino online',
    'poker online uang asli',
    'situs gacor hari ini',
    'pola gacor malam ini',
    'rtp live akurat',
    'rtp slot tertinggi',
    'jam gacor main slot',
    'bocoran slot gacor',
    'bocoran admin slot',
    'akun pro vip',
    'akun wso asli',
    'mix parlay jalan',
    'sabung ayam online',
    'tembak ikan online',
    'anti rungkad terbukti',
    'jackpot progresif',
    'pragmatic play',
    'pg soft',
    'mahjong ways',
    'gates of olympus',

    // === Situs & Platform ===
    // Frasa yang secara langsung merujuk pada entitas penyedia layanan
    // judi online, seringkali dengan penekanan pada 'kepercayaan' atau 'resmi'.
    'link alternatif resmi',
    'situs terpercaya',
    'situs anti rungkad',
    'situs slot terbaik',
    'situs judi online',
    'situs resmi dan terpercaya',
    'agen slot terpercaya',
    'agen resmi',
    'agen judi terpercaya',
    'bandar judi online',
    'bandar togel terpercaya',
    'bandar bola resmi',
    'platform game online',

    // === Transaksi ===
    // Frasa yang berkaitan dengan proses deposit dan penarikan dana,
    // seringkali menonjolkan kemudahan dan keuntungan finansial.
    'deposit pulsa tanpa potongan',
    'depo via pulsa',
    'deposit via dana',
    'deposit via qris',
    'depo 10k wd 50k',
    'minimal depo 10k',
    'minimal deposit',
    'deposit aman',
    'deposit tanpa potongan',
    'wd tanpa batas',
    'proses wd cepat',
    'proses depo wd cepat',
    'transaksi 24 jam',
    'withdraw cepat',

    // === Lain-lain & Seruan Spam ===
    // Frasa pendukung yang sering menyertai promosi utama untuk
    // membangun kepercayaan atau menciptakan kesan eksklusif.
    'jangan bilang siapa siapa',
    'rahasia menang slot',
    'rahasia jp',
    'layanan 24 jam nonstop',
    'customer service online',
    'live chat 24 jam',
    'akun hoki',
    'dijamin hoki',
    'pasti profit',
    'cuma di sini',
    'terbukti membayar',
    'aman dan terpercaya',
    'gabung komunitas',
    'info lebih lanjut',

    // === Brand Spesifik ===
    // Contoh nama brand atau situs yang sering muncul. Daftar ini
    // perlu diperbarui secara berkala seiring munculnya situs-situs baru.
    'king88',
    'k1ng88',
    'king_88',
    'slot88',
    'gacor77',
    'hoki188',
    'jp99',
    'maxwin138',
    'slotmania',
    'zeus88',
    'olympus88',
    'agen138',
    'raja slot',
    'dewa slot',
    'juragan69',
    'cuan88',
    'qqslot',
    'mpo slot',
];
