// src/utils/knownSpamPhrases.js

// Daftar frasa Judol/Spam yang lebih lengkap untuk fuzzy matching atau pencocokan langsung.
// Daftar ini mencakup berbagai variasi kata kunci terkait judi online, promosi,
// ajakan, dan istilah umum yang digunakan dalam spam.
export const knownSpamPhrasesSimple = [
    // Ajakan dan Instruksi
    'daftar sekarang',
    'klik link',
    'link di bio',
    'gabung sekarang',
    'join grup',
    'masuk grup',
    'link grup wa',
    'link telegram',
    'chat admin',
    'hubungi kami',
    'kontak admin',
    'nomor wa',
    'login situs',
    'link login',
    'main sekarang',
    'coba gratis',
    'download aplikasi',
    'buka blokir',
    'anti banned',

    // Bonus dan Promosi
    'bonus new member',
    'bonus member baru',
    'bonus deposit',
    'bonus harian',
    'bonus mingguan',
    'bonus referral',
    'bonus rollingan',
    'bonus cashback',
    'bonus turnover',
    'freebet',
    'saldo gratis',
    'pulsa gratis',
    'dana kaget',
    'link dana kaget',
    'promo terbatas',
    'event menarik',
    'hadiah langsung',
    'klaim bonus',
    'kode promo',
    'voucher gratis',
    'dapatkan bonus',

    // Kemenangan dan Keuntungan
    'jp pasti',
    'auto jp',
    'jp besar',
    'jp kecil',
    'wd aman',
    'pasti bayar',
    'wd cepat',
    'wd lancar',
    'withdraw cepat',
    'withdraw aman',
    'gampang menang',
    'menang banyak',
    'menang setiap hari',
    'cuan',
    'cuan tiap putaran',
    'profit konsisten',
    'dijamin profit',
    'modal kecil untung besar',
    'untung jutaan',
    'kaya mendadak',
    'solusi finansial',
    'bebas hutang',
    'cara cepat kaya',
    'pasif income',
    'uang tambahan',
    'kerja online',
    'bisnis online',
    'bukti jp',
    'hasil jp',
    '100 pasti wd',
    '100 dijamin bayar',

    // Istilah Judi Online Spesifik
    'slot online',
    'togel online',
    'live casino',
    'poker online',
    'dominoqq',
    'bandarqq',
    'situs gacor',
    'pola gacor',
    'rtp live',
    'rtp tertinggi',
    'jam gacor',
    'trik menang',
    'bocoran slot',
    'maxwin',
    'scatter',
    'bigwin',
    'megawin',
    'judi online',
    'akun pro',
    'akun vip',
    'modal receh',
    'parlay',
    'mix parlay',
    'betting',
    'toto',
    'pragmatic',
    'super gacor',
    'anti rungkad',
    'rungkat',
    'pasang nomor',
    'tebak angka',
    '4d', '3d', '2d', // Dimensi togel
    'colok bebas',
    'shio',
    'putaran gratis',
    'free spin',
    'jackpot progresif',
    'turnamen slot',
    'event slot',
    'promo judi',

    // Situs dan Platform
    'link alternatif',
    'situs terpercaya',
    'situs terbaik',
    'situs terbesar',
    'situs resmi',
    'agen slot',
    'bandar judi',
    'situs slot',

    // Transaksi
    'deposit pulsa',
    'deposit via dana',
    'deposit via ovo',
    'deposit via gopay',
    'deposit via linkaja',
    'deposit bank',
    'deposit minimal',
    'withdraw maksimal',
    'proses cepat',

    // Lain-lain (Sering Digunakan dalam Konteks Spam)
    'jangan lewatkan',
    'jangan bilang siapa siapa',
    'rahasia menang',
    'bocoran rahasia',
    'panduan lengkap',
    'tips dan trik',
    'trik jitu',
    'pola jitu',
    'jam hoki',
    'jam keberuntungan',
    'jangan ragu',
    'buktikan sendiri',
    'pengalaman member',
    'layanan 24 jam',
    'customer service',
    'cs online',
    'live chat',
    'id data', // Sering terkait dengan pendaftaran
    'testimoni',
    'review jujur', // Sering digunakan secara ironis oleh scammer
    'link viral', // Sering mengarah ke situs spam/phishing
    'video viral', // Sering mengarah ke situs spam/phishing
    'akun hoki',
    'akun super',
    'akun dewa',
    'daftar akun',
    'bikin akun',
    'cara daftar',
];

// Anda bisa mengimpor daftar ini di file lain, misalnya di judolSpamPatterns.js
// atau di komponen/fungsi yang melakukan deteksi spam.
// Contoh impor:
// import { knownSpamPhrasesSimple } from './knownSpamPhrases';
